class ArticleEntity:
    id: int
    created_at: str
    title: str
    description: str
    images: list[str]
    status: bool
    condition: float
    type: str
    category_id: int
    change_to: str
    num_likes: int
    user: str
    corpus: str
    category: str
